/*
* Order:
* -- id (integer, autogenerated)
* -- customerName(string, required)
* -- totalAmount(decimal/number, required>0)
* -- state(string, one of: CREATED, APPROVED, PAID, SHIPPED, CLOSED)
* -- createdAt, UpdatedAt (timestamps, set by system)
*
* */


package com.learn.Task2.model.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Builder;

import java.math.BigDecimal;
import java.time.LocalDateTime;


@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Order {

    private Long id;

    private String customerName;

    private BigDecimal totalAmount;

    private OrderState state;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;
}
